/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif

// Avoid multiple includes of SherpaOnnxSpec symbols
#ifndef SherpaOnnxSpec_H
#define SherpaOnnxSpec_H

#import <Foundation/Foundation.h>
#import <RCTRequired/RCTRequired.h>
#import <RCTTypeSafety/RCTConvertHelpers.h>
#import <RCTTypeSafety/RCTTypedModuleConstants.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTCxxConvert.h>
#import <React/RCTManagedPointer.h>
#import <ReactCommon/RCTTurboModule.h>
#import <optional>
#import <vector>


NS_ASSUME_NONNULL_BEGIN
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitTtsConfig {
      NSString *modelDir() const;
      NSString *modelType() const;
      NSString *modelFile() const;
      NSString *tokensFile() const;
      NSString *acousticModelName() const;
      NSString *vocoder() const;
      NSString *voices() const;
      NSString *lexicon() const;
      NSString *dataDir() const;
      NSString *dictDir() const;
      NSString *ruleFsts() const;
      NSString *ruleFars() const;
      std::optional<double> numThreads() const;
      std::optional<bool> debug() const;
      std::optional<double> noiseScale() const;
      std::optional<double> noiseScaleW() const;
      std::optional<double> lengthScale() const;
      NSString *lang() const;

      SpecInitTtsConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitTtsConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitTtsConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecGenerateTtsConfig {
      NSString *text() const;
      double speakerId() const;
      double speakingRate() const;
      bool playAudio() const;
      NSString *fileNamePrefix() const;
      std::optional<double> lengthScale() const;
      std::optional<double> noiseScale() const;
      std::optional<double> noiseScaleW() const;

      SpecGenerateTtsConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecGenerateTtsConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecGenerateTtsConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitAsrConfig {
      NSString *modelDir() const;
      NSString *modelType() const;
      NSString *modelPath() const;
      std::optional<double> numThreads() const;
      std::optional<bool> debug() const;
      std::optional<bool> streaming() const;
      std::optional<double> sampleRate() const;
      std::optional<double> featureDim() const;
      NSString *decodingMethod() const;
      std::optional<double> maxActivePaths() const;
      NSString *provider() const;
      NSString *language() const;
      NSString *task() const;
      std::optional<bool> useItn() const;
      NSString *srcLang() const;
      NSString *tgtLang() const;
      std::optional<bool> usePnc() const;
      std::optional<bool> usePunct() const;
      NSString *hotwords() const;
      std::optional<double> qwen3MaxTotalLen() const;
      std::optional<double> qwen3MaxNewTokens() const;
      std::optional<double> qwen3Temperature() const;
      std::optional<double> qwen3TopP() const;
      std::optional<double> qwen3Seed() const;
      NSString *modelFileEncoder() const;
      NSString *modelFileDecoder() const;
      NSString *modelFileJoiner() const;
      NSString *modelFileTokens() const;
      NSString *modelFileModel() const;
      NSString *modelFilePreprocessor() const;
      NSString *modelFileUncachedDecoder() const;
      NSString *modelFileCachedDecoder() const;
      NSString *modelFileConvFrontend() const;
      NSString *modelFileTokenizer() const;

      SpecInitAsrConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitAsrConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitAsrConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitAudioTaggingConfig {
      NSString *modelDir() const;
      NSString *modelType() const;
      NSString *modelName() const;
      NSString *modelFile() const;
      NSString *labelsFile() const;
      std::optional<double> numThreads() const;
      std::optional<double> topK() const;
      std::optional<bool> debug() const;

      SpecInitAudioTaggingConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitAudioTaggingConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitAudioTaggingConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitSpeakerIdConfig {
      NSString *modelDir() const;
      NSString *modelFile() const;
      NSString *modelType() const;
      std::optional<double> sampleRate() const;
      std::optional<double> numThreads() const;
      NSString *provider() const;
      std::optional<bool> debug() const;

      SpecInitSpeakerIdConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitSpeakerIdConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitSpeakerIdConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitDiarizationConfig {
      NSString *segmentationModelDir() const;
      NSString *segmentationModelFile() const;
      NSString *embeddingModelFile() const;
      std::optional<double> numThreads() const;
      std::optional<bool> debug() const;
      NSString *provider() const;
      std::optional<double> minDurationOn() const;
      std::optional<double> minDurationOff() const;
      std::optional<double> numClusters() const;
      std::optional<double> threshold() const;

      SpecInitDiarizationConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitDiarizationConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitDiarizationConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitKwsConfig {
      NSString *modelDir() const;
      NSString *modelType() const;
      NSString *modelFileEncoder() const;
      NSString *modelFileDecoder() const;
      NSString *modelFileJoiner() const;
      NSString *modelFileTokens() const;
      NSString *keywordsFile() const;
      std::optional<double> numThreads() const;
      std::optional<bool> debug() const;
      NSString *provider() const;
      std::optional<double> maxActivePaths() const;
      std::optional<double> keywordsScore() const;
      std::optional<double> keywordsThreshold() const;
      std::optional<double> numTrailingBlanks() const;

      SpecInitKwsConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitKwsConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitKwsConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitVadConfig {
      NSString *modelDir() const;
      NSString *modelFile() const;
      std::optional<double> threshold() const;
      std::optional<double> minSilenceDuration() const;
      std::optional<double> minSpeechDuration() const;
      std::optional<double> windowSize() const;
      std::optional<double> maxSpeechDuration() const;
      std::optional<double> bufferSizeInSeconds() const;
      std::optional<double> numThreads() const;
      std::optional<bool> debug() const;
      NSString *provider() const;

      SpecInitVadConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitVadConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitVadConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitLanguageIdConfig {
      NSString *modelDir() const;
      NSString *encoderFile() const;
      NSString *decoderFile() const;
      std::optional<double> numThreads() const;
      std::optional<bool> debug() const;
      NSString *provider() const;

      SpecInitLanguageIdConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitLanguageIdConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitLanguageIdConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitPunctuationConfig {
      NSString *modelDir() const;
      NSString *cnnBilstm() const;
      NSString *bpeVocab() const;
      std::optional<double> numThreads() const;
      std::optional<bool> debug() const;
      NSString *provider() const;

      SpecInitPunctuationConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitPunctuationConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitPunctuationConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecInitDenoiserConfig {
      NSString *modelFile() const;
      std::optional<double> numThreads() const;
      NSString *provider() const;
      std::optional<bool> debug() const;

      SpecInitDenoiserConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitDenoiserConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitDenoiserConfig:(id)json;
@end
namespace JS {
  namespace NativeSherpaOnnxSpec {
    struct SpecCreateOnnxSessionConfig {
      NSString *modelPath() const;
      std::optional<double> numThreads() const;

      SpecCreateOnnxSessionConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeSherpaOnnxSpec_SpecCreateOnnxSessionConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecCreateOnnxSessionConfig:(id)json;
@end
@protocol NativeSherpaOnnxSpecSpec <RCTBridgeModule, RCTTurboModule>

- (void)validateLibraryLoaded:(RCTPromiseResolveBlock)resolve
                       reject:(RCTPromiseRejectBlock)reject;
- (void)testOnnxIntegration:(RCTPromiseResolveBlock)resolve
                     reject:(RCTPromiseRejectBlock)reject;
- (void)getArchitectureInfo:(RCTPromiseResolveBlock)resolve
                     reject:(RCTPromiseRejectBlock)reject;
- (void)getSystemInfo:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject;
- (void)initTts:(JS::NativeSherpaOnnxSpec::SpecInitTtsConfig &)config
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject;
- (void)generateTts:(JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig &)config
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;
- (void)stopTts:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject;
- (void)releaseTts:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject;
- (void)initAsr:(JS::NativeSherpaOnnxSpec::SpecInitAsrConfig &)config
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject;
- (void)recognizeFromSamples:(double)sampleRate
                     samples:(NSArray *)samples
                     resolve:(RCTPromiseResolveBlock)resolve
                      reject:(RCTPromiseRejectBlock)reject;
- (void)recognizeFromFile:(NSString *)filePath
                  resolve:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject;
- (void)releaseAsr:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject;
- (void)createAsrOnlineStream:(RCTPromiseResolveBlock)resolve
                       reject:(RCTPromiseRejectBlock)reject;
- (void)acceptAsrOnlineWaveform:(double)sampleRate
                        samples:(NSArray *)samples
                        resolve:(RCTPromiseResolveBlock)resolve
                         reject:(RCTPromiseRejectBlock)reject;
- (void)isAsrOnlineEndpoint:(RCTPromiseResolveBlock)resolve
                     reject:(RCTPromiseRejectBlock)reject;
- (void)getAsrOnlineResult:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject;
- (void)resetAsrOnlineStream:(RCTPromiseResolveBlock)resolve
                      reject:(RCTPromiseRejectBlock)reject;
- (void)initAudioTagging:(JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig &)config
                 resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject;
- (void)processAndComputeAudioTagging:(NSString *)filePath
                              resolve:(RCTPromiseResolveBlock)resolve
                               reject:(RCTPromiseRejectBlock)reject;
- (void)processAndComputeAudioSamples:(double)sampleRate
                              samples:(NSArray *)samples
                              resolve:(RCTPromiseResolveBlock)resolve
                               reject:(RCTPromiseRejectBlock)reject;
- (void)releaseAudioTagging:(RCTPromiseResolveBlock)resolve
                     reject:(RCTPromiseRejectBlock)reject;
- (void)initSpeakerId:(JS::NativeSherpaOnnxSpec::SpecInitSpeakerIdConfig &)config
              resolve:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject;
- (void)processSpeakerIdSamples:(double)sampleRate
                        samples:(NSArray *)samples
                        resolve:(RCTPromiseResolveBlock)resolve
                         reject:(RCTPromiseRejectBlock)reject;
- (void)computeSpeakerEmbedding:(RCTPromiseResolveBlock)resolve
                         reject:(RCTPromiseRejectBlock)reject;
- (void)registerSpeaker:(NSString *)name
              embedding:(NSArray *)embedding
                resolve:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject;
- (void)removeSpeaker:(NSString *)name
              resolve:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject;
- (void)getSpeakers:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;
- (void)identifySpeaker:(NSArray *)embedding
              threshold:(double)threshold
                resolve:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject;
- (void)verifySpeaker:(NSString *)name
            embedding:(NSArray *)embedding
            threshold:(double)threshold
              resolve:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject;
- (void)processSpeakerIdFile:(NSString *)filePath
                     resolve:(RCTPromiseResolveBlock)resolve
                      reject:(RCTPromiseRejectBlock)reject;
- (void)processSpeakerIdFileWindow:(NSString *)filePath
                       startTimeMs:(double)startTimeMs
                        durationMs:(double)durationMs
                           resolve:(RCTPromiseResolveBlock)resolve
                            reject:(RCTPromiseRejectBlock)reject;
- (void)releaseSpeakerId:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject;
- (void)initDiarization:(JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig &)config
                resolve:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject;
- (void)processDiarizationFile:(NSString *)filePath
                   numClusters:(double)numClusters
                     threshold:(double)threshold
                       resolve:(RCTPromiseResolveBlock)resolve
                        reject:(RCTPromiseRejectBlock)reject;
- (void)processDiarizationFileWindow:(NSString *)filePath
                         startTimeMs:(double)startTimeMs
                          durationMs:(double)durationMs
                         numClusters:(double)numClusters
                           threshold:(double)threshold
                             resolve:(RCTPromiseResolveBlock)resolve
                              reject:(RCTPromiseRejectBlock)reject;
- (void)releaseDiarization:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject;
- (void)initKws:(JS::NativeSherpaOnnxSpec::SpecInitKwsConfig &)config
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject;
- (void)acceptKwsWaveform:(double)sampleRate
                  samples:(NSArray *)samples
                  resolve:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject;
- (void)resetKwsStream:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject;
- (void)releaseKws:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject;
- (void)initVad:(JS::NativeSherpaOnnxSpec::SpecInitVadConfig &)config
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject;
- (void)acceptVadWaveform:(double)sampleRate
                  samples:(NSArray *)samples
                  resolve:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject;
- (void)resetVad:(RCTPromiseResolveBlock)resolve
          reject:(RCTPromiseRejectBlock)reject;
- (void)releaseVad:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject;
- (void)initLanguageId:(JS::NativeSherpaOnnxSpec::SpecInitLanguageIdConfig &)config
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject;
- (void)detectLanguage:(double)sampleRate
               samples:(NSArray *)samples
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject;
- (void)detectLanguageFromFile:(NSString *)filePath
                       resolve:(RCTPromiseResolveBlock)resolve
                        reject:(RCTPromiseRejectBlock)reject;
- (void)releaseLanguageId:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject;
- (void)initPunctuation:(JS::NativeSherpaOnnxSpec::SpecInitPunctuationConfig &)config
                resolve:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject;
- (void)addPunctuation:(NSString *)text
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject;
- (void)releasePunctuation:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject;
- (void)initDenoiser:(JS::NativeSherpaOnnxSpec::SpecInitDenoiserConfig &)config
             resolve:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject;
- (void)denoiseFile:(NSString *)filePath
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;
- (void)releaseDenoiser:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject;
- (void)createOnnxSession:(JS::NativeSherpaOnnxSpec::SpecCreateOnnxSessionConfig &)config
                  resolve:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject;
- (void)runOnnxSession:(NSString *)sessionId
            inputNames:(NSArray *)inputNames
            inputTypes:(NSArray *)inputTypes
             inputDims:(NSArray *)inputDims
             inputData:(NSArray *)inputData
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject;
- (void)releaseOnnxSession:(NSString *)sessionId
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject;
- (void)extractTarBz2:(NSString *)sourcePath
            targetDir:(NSString *)targetDir
              resolve:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject;

@end

@interface NativeSherpaOnnxSpecSpecBase : NSObject {
@protected
facebook::react::EventEmitterCallback _eventEmitterCallback;
}
- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper;


@end

namespace facebook::react {
  /**
   * ObjC++ class for module 'NativeSherpaOnnxSpec'
   */
  class JSI_EXPORT NativeSherpaOnnxSpecSpecJSI : public ObjCTurboModule {
  public:
    NativeSherpaOnnxSpecSpecJSI(const ObjCTurboModule::InitParams &params);
  };
} // namespace facebook::react
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::modelDir() const
{
  id const p = _v[@"modelDir"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::modelType() const
{
  id const p = _v[@"modelType"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::modelFile() const
{
  id const p = _v[@"modelFile"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::tokensFile() const
{
  id const p = _v[@"tokensFile"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::acousticModelName() const
{
  id const p = _v[@"acousticModelName"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::vocoder() const
{
  id const p = _v[@"vocoder"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::voices() const
{
  id const p = _v[@"voices"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::lexicon() const
{
  id const p = _v[@"lexicon"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::dataDir() const
{
  id const p = _v[@"dataDir"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::dictDir() const
{
  id const p = _v[@"dictDir"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::ruleFsts() const
{
  id const p = _v[@"ruleFsts"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::ruleFars() const
{
  id const p = _v[@"ruleFars"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::noiseScale() const
{
  id const p = _v[@"noiseScale"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::noiseScaleW() const
{
  id const p = _v[@"noiseScaleW"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::lengthScale() const
{
  id const p = _v[@"lengthScale"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitTtsConfig::lang() const
{
  id const p = _v[@"lang"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig::text() const
{
  id const p = _v[@"text"];
  return RCTBridgingToString(p);
}
inline double JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig::speakerId() const
{
  id const p = _v[@"speakerId"];
  return RCTBridgingToDouble(p);
}
inline double JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig::speakingRate() const
{
  id const p = _v[@"speakingRate"];
  return RCTBridgingToDouble(p);
}
inline bool JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig::playAudio() const
{
  id const p = _v[@"playAudio"];
  return RCTBridgingToBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig::fileNamePrefix() const
{
  id const p = _v[@"fileNamePrefix"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig::lengthScale() const
{
  id const p = _v[@"lengthScale"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig::noiseScale() const
{
  id const p = _v[@"noiseScale"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig::noiseScaleW() const
{
  id const p = _v[@"noiseScaleW"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelDir() const
{
  id const p = _v[@"modelDir"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelType() const
{
  id const p = _v[@"modelType"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelPath() const
{
  id const p = _v[@"modelPath"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::streaming() const
{
  id const p = _v[@"streaming"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::sampleRate() const
{
  id const p = _v[@"sampleRate"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::featureDim() const
{
  id const p = _v[@"featureDim"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::decodingMethod() const
{
  id const p = _v[@"decodingMethod"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::maxActivePaths() const
{
  id const p = _v[@"maxActivePaths"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::provider() const
{
  id const p = _v[@"provider"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::language() const
{
  id const p = _v[@"language"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::task() const
{
  id const p = _v[@"task"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::useItn() const
{
  id const p = _v[@"useItn"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::srcLang() const
{
  id const p = _v[@"srcLang"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::tgtLang() const
{
  id const p = _v[@"tgtLang"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::usePnc() const
{
  id const p = _v[@"usePnc"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::usePunct() const
{
  id const p = _v[@"usePunct"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::hotwords() const
{
  id const p = _v[@"hotwords"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::qwen3MaxTotalLen() const
{
  id const p = _v[@"qwen3MaxTotalLen"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::qwen3MaxNewTokens() const
{
  id const p = _v[@"qwen3MaxNewTokens"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::qwen3Temperature() const
{
  id const p = _v[@"qwen3Temperature"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::qwen3TopP() const
{
  id const p = _v[@"qwen3TopP"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::qwen3Seed() const
{
  id const p = _v[@"qwen3Seed"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFileEncoder() const
{
  id const p = _v[@"modelFileEncoder"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFileDecoder() const
{
  id const p = _v[@"modelFileDecoder"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFileJoiner() const
{
  id const p = _v[@"modelFileJoiner"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFileTokens() const
{
  id const p = _v[@"modelFileTokens"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFileModel() const
{
  id const p = _v[@"modelFileModel"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFilePreprocessor() const
{
  id const p = _v[@"modelFilePreprocessor"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFileUncachedDecoder() const
{
  id const p = _v[@"modelFileUncachedDecoder"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFileCachedDecoder() const
{
  id const p = _v[@"modelFileCachedDecoder"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFileConvFrontend() const
{
  id const p = _v[@"modelFileConvFrontend"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAsrConfig::modelFileTokenizer() const
{
  id const p = _v[@"modelFileTokenizer"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig::modelDir() const
{
  id const p = _v[@"modelDir"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig::modelType() const
{
  id const p = _v[@"modelType"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig::modelName() const
{
  id const p = _v[@"modelName"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig::modelFile() const
{
  id const p = _v[@"modelFile"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig::labelsFile() const
{
  id const p = _v[@"labelsFile"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig::topK() const
{
  id const p = _v[@"topK"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitSpeakerIdConfig::modelDir() const
{
  id const p = _v[@"modelDir"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitSpeakerIdConfig::modelFile() const
{
  id const p = _v[@"modelFile"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitSpeakerIdConfig::modelType() const
{
  id const p = _v[@"modelType"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitSpeakerIdConfig::sampleRate() const
{
  id const p = _v[@"sampleRate"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitSpeakerIdConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitSpeakerIdConfig::provider() const
{
  id const p = _v[@"provider"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitSpeakerIdConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::segmentationModelDir() const
{
  id const p = _v[@"segmentationModelDir"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::segmentationModelFile() const
{
  id const p = _v[@"segmentationModelFile"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::embeddingModelFile() const
{
  id const p = _v[@"embeddingModelFile"];
  return RCTBridgingToString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::provider() const
{
  id const p = _v[@"provider"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::minDurationOn() const
{
  id const p = _v[@"minDurationOn"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::minDurationOff() const
{
  id const p = _v[@"minDurationOff"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::numClusters() const
{
  id const p = _v[@"numClusters"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig::threshold() const
{
  id const p = _v[@"threshold"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::modelDir() const
{
  id const p = _v[@"modelDir"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::modelType() const
{
  id const p = _v[@"modelType"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::modelFileEncoder() const
{
  id const p = _v[@"modelFileEncoder"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::modelFileDecoder() const
{
  id const p = _v[@"modelFileDecoder"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::modelFileJoiner() const
{
  id const p = _v[@"modelFileJoiner"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::modelFileTokens() const
{
  id const p = _v[@"modelFileTokens"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::keywordsFile() const
{
  id const p = _v[@"keywordsFile"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::provider() const
{
  id const p = _v[@"provider"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::maxActivePaths() const
{
  id const p = _v[@"maxActivePaths"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::keywordsScore() const
{
  id const p = _v[@"keywordsScore"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::keywordsThreshold() const
{
  id const p = _v[@"keywordsThreshold"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitKwsConfig::numTrailingBlanks() const
{
  id const p = _v[@"numTrailingBlanks"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitVadConfig::modelDir() const
{
  id const p = _v[@"modelDir"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitVadConfig::modelFile() const
{
  id const p = _v[@"modelFile"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitVadConfig::threshold() const
{
  id const p = _v[@"threshold"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitVadConfig::minSilenceDuration() const
{
  id const p = _v[@"minSilenceDuration"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitVadConfig::minSpeechDuration() const
{
  id const p = _v[@"minSpeechDuration"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitVadConfig::windowSize() const
{
  id const p = _v[@"windowSize"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitVadConfig::maxSpeechDuration() const
{
  id const p = _v[@"maxSpeechDuration"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitVadConfig::bufferSizeInSeconds() const
{
  id const p = _v[@"bufferSizeInSeconds"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitVadConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitVadConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitVadConfig::provider() const
{
  id const p = _v[@"provider"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitLanguageIdConfig::modelDir() const
{
  id const p = _v[@"modelDir"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitLanguageIdConfig::encoderFile() const
{
  id const p = _v[@"encoderFile"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitLanguageIdConfig::decoderFile() const
{
  id const p = _v[@"decoderFile"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitLanguageIdConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitLanguageIdConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitLanguageIdConfig::provider() const
{
  id const p = _v[@"provider"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitPunctuationConfig::modelDir() const
{
  id const p = _v[@"modelDir"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitPunctuationConfig::cnnBilstm() const
{
  id const p = _v[@"cnnBilstm"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitPunctuationConfig::bpeVocab() const
{
  id const p = _v[@"bpeVocab"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitPunctuationConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitPunctuationConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitPunctuationConfig::provider() const
{
  id const p = _v[@"provider"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitDenoiserConfig::modelFile() const
{
  id const p = _v[@"modelFile"];
  return RCTBridgingToString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecInitDenoiserConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecInitDenoiserConfig::provider() const
{
  id const p = _v[@"provider"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<bool> JS::NativeSherpaOnnxSpec::SpecInitDenoiserConfig::debug() const
{
  id const p = _v[@"debug"];
  return RCTBridgingToOptionalBool(p);
}
inline NSString *JS::NativeSherpaOnnxSpec::SpecCreateOnnxSessionConfig::modelPath() const
{
  id const p = _v[@"modelPath"];
  return RCTBridgingToString(p);
}
inline std::optional<double> JS::NativeSherpaOnnxSpec::SpecCreateOnnxSessionConfig::numThreads() const
{
  id const p = _v[@"numThreads"];
  return RCTBridgingToOptionalDouble(p);
}
NS_ASSUME_NONNULL_END
#endif // SherpaOnnxSpec_H
