/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#import "SherpaOnnxSpec.h"


@implementation NativeSherpaOnnxSpecSpecBase


- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper
{
  _eventEmitterCallback = std::move(eventEmitterCallbackWrapper->_eventEmitterCallback);
}
@end

@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitTtsConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitTtsConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitTtsConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecGenerateTtsConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecGenerateTtsConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecGenerateTtsConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitAsrConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitAsrConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitAsrConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitAudioTaggingConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitAudioTaggingConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitAudioTaggingConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitSpeakerIdConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitSpeakerIdConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitSpeakerIdConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitDiarizationConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitDiarizationConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitDiarizationConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitKwsConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitKwsConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitKwsConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitVadConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitVadConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitVadConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitLanguageIdConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitLanguageIdConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitLanguageIdConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitPunctuationConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitPunctuationConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitPunctuationConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecInitDenoiserConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecInitDenoiserConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecInitDenoiserConfig>(json);
}
@end
@implementation RCTCxxConvert (NativeSherpaOnnxSpec_SpecCreateOnnxSessionConfig)
+ (RCTManagedPointer *)JS_NativeSherpaOnnxSpec_SpecCreateOnnxSessionConfig:(id)json
{
  return facebook::react::managedPointer<JS::NativeSherpaOnnxSpec::SpecCreateOnnxSessionConfig>(json);
}
@end
namespace facebook::react {

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_validateLibraryLoaded(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "validateLibraryLoaded", @selector(validateLibraryLoaded:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_testOnnxIntegration(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "testOnnxIntegration", @selector(testOnnxIntegration:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_getArchitectureInfo(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "getArchitectureInfo", @selector(getArchitectureInfo:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_getSystemInfo(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "getSystemInfo", @selector(getSystemInfo:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initTts(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initTts", @selector(initTts:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_generateTts(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "generateTts", @selector(generateTts:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_stopTts(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "stopTts", @selector(stopTts:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseTts(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseTts", @selector(releaseTts:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initAsr(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initAsr", @selector(initAsr:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_recognizeFromSamples(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "recognizeFromSamples", @selector(recognizeFromSamples:samples:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_recognizeFromFile(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "recognizeFromFile", @selector(recognizeFromFile:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseAsr(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseAsr", @selector(releaseAsr:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_createAsrOnlineStream(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "createAsrOnlineStream", @selector(createAsrOnlineStream:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_acceptAsrOnlineWaveform(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "acceptAsrOnlineWaveform", @selector(acceptAsrOnlineWaveform:samples:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_isAsrOnlineEndpoint(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "isAsrOnlineEndpoint", @selector(isAsrOnlineEndpoint:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_getAsrOnlineResult(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "getAsrOnlineResult", @selector(getAsrOnlineResult:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_resetAsrOnlineStream(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "resetAsrOnlineStream", @selector(resetAsrOnlineStream:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initAudioTagging(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initAudioTagging", @selector(initAudioTagging:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_processAndComputeAudioTagging(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "processAndComputeAudioTagging", @selector(processAndComputeAudioTagging:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_processAndComputeAudioSamples(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "processAndComputeAudioSamples", @selector(processAndComputeAudioSamples:samples:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseAudioTagging(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseAudioTagging", @selector(releaseAudioTagging:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initSpeakerId(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initSpeakerId", @selector(initSpeakerId:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_processSpeakerIdSamples(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "processSpeakerIdSamples", @selector(processSpeakerIdSamples:samples:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_computeSpeakerEmbedding(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "computeSpeakerEmbedding", @selector(computeSpeakerEmbedding:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_registerSpeaker(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "registerSpeaker", @selector(registerSpeaker:embedding:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_removeSpeaker(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "removeSpeaker", @selector(removeSpeaker:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_getSpeakers(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "getSpeakers", @selector(getSpeakers:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_identifySpeaker(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "identifySpeaker", @selector(identifySpeaker:threshold:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_verifySpeaker(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "verifySpeaker", @selector(verifySpeaker:embedding:threshold:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_processSpeakerIdFile(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "processSpeakerIdFile", @selector(processSpeakerIdFile:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_processSpeakerIdFileWindow(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "processSpeakerIdFileWindow", @selector(processSpeakerIdFileWindow:startTimeMs:durationMs:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseSpeakerId(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseSpeakerId", @selector(releaseSpeakerId:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initDiarization(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initDiarization", @selector(initDiarization:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_processDiarizationFile(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "processDiarizationFile", @selector(processDiarizationFile:numClusters:threshold:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_processDiarizationFileWindow(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "processDiarizationFileWindow", @selector(processDiarizationFileWindow:startTimeMs:durationMs:numClusters:threshold:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseDiarization(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseDiarization", @selector(releaseDiarization:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initKws(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initKws", @selector(initKws:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_acceptKwsWaveform(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "acceptKwsWaveform", @selector(acceptKwsWaveform:samples:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_resetKwsStream(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "resetKwsStream", @selector(resetKwsStream:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseKws(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseKws", @selector(releaseKws:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initVad(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initVad", @selector(initVad:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_acceptVadWaveform(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "acceptVadWaveform", @selector(acceptVadWaveform:samples:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_resetVad(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "resetVad", @selector(resetVad:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseVad(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseVad", @selector(releaseVad:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initLanguageId(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initLanguageId", @selector(initLanguageId:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_detectLanguage(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "detectLanguage", @selector(detectLanguage:samples:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_detectLanguageFromFile(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "detectLanguageFromFile", @selector(detectLanguageFromFile:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseLanguageId(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseLanguageId", @selector(releaseLanguageId:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initPunctuation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initPunctuation", @selector(initPunctuation:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_addPunctuation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "addPunctuation", @selector(addPunctuation:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releasePunctuation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releasePunctuation", @selector(releasePunctuation:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_initDenoiser(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initDenoiser", @selector(initDenoiser:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_denoiseFile(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "denoiseFile", @selector(denoiseFile:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseDenoiser(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseDenoiser", @selector(releaseDenoiser:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_createOnnxSession(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "createOnnxSession", @selector(createOnnxSession:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_runOnnxSession(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "runOnnxSession", @selector(runOnnxSession:inputNames:inputTypes:inputDims:inputData:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseOnnxSession(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "releaseOnnxSession", @selector(releaseOnnxSession:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeSherpaOnnxSpecSpecJSI_extractTarBz2(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "extractTarBz2", @selector(extractTarBz2:targetDir:resolve:reject:), args, count);
    }

  NativeSherpaOnnxSpecSpecJSI::NativeSherpaOnnxSpecSpecJSI(const ObjCTurboModule::InitParams &params)
    : ObjCTurboModule(params) {

        methodMap_["validateLibraryLoaded"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_validateLibraryLoaded};


        methodMap_["testOnnxIntegration"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_testOnnxIntegration};


        methodMap_["getArchitectureInfo"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_getArchitectureInfo};


        methodMap_["getSystemInfo"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_getSystemInfo};


        methodMap_["initTts"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initTts};
        setMethodArgConversionSelector(@"initTts", 0, @"JS_NativeSherpaOnnxSpec_SpecInitTtsConfig:");

        methodMap_["generateTts"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_generateTts};
        setMethodArgConversionSelector(@"generateTts", 0, @"JS_NativeSherpaOnnxSpec_SpecGenerateTtsConfig:");

        methodMap_["stopTts"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_stopTts};


        methodMap_["releaseTts"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseTts};


        methodMap_["initAsr"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initAsr};
        setMethodArgConversionSelector(@"initAsr", 0, @"JS_NativeSherpaOnnxSpec_SpecInitAsrConfig:");

        methodMap_["recognizeFromSamples"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_recognizeFromSamples};


        methodMap_["recognizeFromFile"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_recognizeFromFile};


        methodMap_["releaseAsr"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseAsr};


        methodMap_["createAsrOnlineStream"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_createAsrOnlineStream};


        methodMap_["acceptAsrOnlineWaveform"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_acceptAsrOnlineWaveform};


        methodMap_["isAsrOnlineEndpoint"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_isAsrOnlineEndpoint};


        methodMap_["getAsrOnlineResult"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_getAsrOnlineResult};


        methodMap_["resetAsrOnlineStream"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_resetAsrOnlineStream};


        methodMap_["initAudioTagging"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initAudioTagging};
        setMethodArgConversionSelector(@"initAudioTagging", 0, @"JS_NativeSherpaOnnxSpec_SpecInitAudioTaggingConfig:");

        methodMap_["processAndComputeAudioTagging"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_processAndComputeAudioTagging};


        methodMap_["processAndComputeAudioSamples"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_processAndComputeAudioSamples};


        methodMap_["releaseAudioTagging"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseAudioTagging};


        methodMap_["initSpeakerId"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initSpeakerId};
        setMethodArgConversionSelector(@"initSpeakerId", 0, @"JS_NativeSherpaOnnxSpec_SpecInitSpeakerIdConfig:");

        methodMap_["processSpeakerIdSamples"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_processSpeakerIdSamples};


        methodMap_["computeSpeakerEmbedding"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_computeSpeakerEmbedding};


        methodMap_["registerSpeaker"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_registerSpeaker};


        methodMap_["removeSpeaker"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_removeSpeaker};


        methodMap_["getSpeakers"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_getSpeakers};


        methodMap_["identifySpeaker"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_identifySpeaker};


        methodMap_["verifySpeaker"] = MethodMetadata {3, __hostFunction_NativeSherpaOnnxSpecSpecJSI_verifySpeaker};


        methodMap_["processSpeakerIdFile"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_processSpeakerIdFile};


        methodMap_["processSpeakerIdFileWindow"] = MethodMetadata {3, __hostFunction_NativeSherpaOnnxSpecSpecJSI_processSpeakerIdFileWindow};


        methodMap_["releaseSpeakerId"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseSpeakerId};


        methodMap_["initDiarization"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initDiarization};
        setMethodArgConversionSelector(@"initDiarization", 0, @"JS_NativeSherpaOnnxSpec_SpecInitDiarizationConfig:");

        methodMap_["processDiarizationFile"] = MethodMetadata {3, __hostFunction_NativeSherpaOnnxSpecSpecJSI_processDiarizationFile};


        methodMap_["processDiarizationFileWindow"] = MethodMetadata {5, __hostFunction_NativeSherpaOnnxSpecSpecJSI_processDiarizationFileWindow};


        methodMap_["releaseDiarization"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseDiarization};


        methodMap_["initKws"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initKws};
        setMethodArgConversionSelector(@"initKws", 0, @"JS_NativeSherpaOnnxSpec_SpecInitKwsConfig:");

        methodMap_["acceptKwsWaveform"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_acceptKwsWaveform};


        methodMap_["resetKwsStream"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_resetKwsStream};


        methodMap_["releaseKws"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseKws};


        methodMap_["initVad"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initVad};
        setMethodArgConversionSelector(@"initVad", 0, @"JS_NativeSherpaOnnxSpec_SpecInitVadConfig:");

        methodMap_["acceptVadWaveform"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_acceptVadWaveform};


        methodMap_["resetVad"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_resetVad};


        methodMap_["releaseVad"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseVad};


        methodMap_["initLanguageId"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initLanguageId};
        setMethodArgConversionSelector(@"initLanguageId", 0, @"JS_NativeSherpaOnnxSpec_SpecInitLanguageIdConfig:");

        methodMap_["detectLanguage"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_detectLanguage};


        methodMap_["detectLanguageFromFile"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_detectLanguageFromFile};


        methodMap_["releaseLanguageId"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseLanguageId};


        methodMap_["initPunctuation"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initPunctuation};
        setMethodArgConversionSelector(@"initPunctuation", 0, @"JS_NativeSherpaOnnxSpec_SpecInitPunctuationConfig:");

        methodMap_["addPunctuation"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_addPunctuation};


        methodMap_["releasePunctuation"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releasePunctuation};


        methodMap_["initDenoiser"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_initDenoiser};
        setMethodArgConversionSelector(@"initDenoiser", 0, @"JS_NativeSherpaOnnxSpec_SpecInitDenoiserConfig:");

        methodMap_["denoiseFile"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_denoiseFile};


        methodMap_["releaseDenoiser"] = MethodMetadata {0, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseDenoiser};


        methodMap_["createOnnxSession"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_createOnnxSession};
        setMethodArgConversionSelector(@"createOnnxSession", 0, @"JS_NativeSherpaOnnxSpec_SpecCreateOnnxSessionConfig:");

        methodMap_["runOnnxSession"] = MethodMetadata {5, __hostFunction_NativeSherpaOnnxSpecSpecJSI_runOnnxSession};


        methodMap_["releaseOnnxSession"] = MethodMetadata {1, __hostFunction_NativeSherpaOnnxSpecSpecJSI_releaseOnnxSession};


        methodMap_["extractTarBz2"] = MethodMetadata {2, __hostFunction_NativeSherpaOnnxSpecSpecJSI_extractTarBz2};

  }
} // namespace facebook::react
